CREATE DATABASE idp_project
CREATE TABLE Docent  (
DocentID INT NOT NULL AUTO_INCREMENT,
Gebruikersnaam VARCHAR(50),
Wachtwoord VARCHAR(50),
Email VARCHAR(50),
PRIMARY KEY(DocentID)
);
CREATE TABLE Klas  (
KlasID INT NOT NULL AUTO_INCREMENT,
DocentID INT NOT NULL,
LampID INT NOT NULL,
PRIMARY KEY(KlasID)
);

CREATE TABLE Lamp  (
LampID INT NOT NULL AUTO_INCREMENT,
SensorID INT NOT NULL ,
PRIMARY KEY(LampID)
);

CREATE TABLE Sensor  (
SensorID INT NOT NULL AUTO_INCREMENT,
Decibel INT NOT NULL,
PRIMARY KEY(SensorID)
);


ALTER TABLE Klas
ADD CONSTRAINT Klas_Docent
FOREIGN KEY (DocentID) REFERENCES Docent(DocentID);

ALTER TABLE Klas
ADD CONSTRAINT Klas_Lamp
FOREIGN KEY (LampID) REFERENCES Lamp(LampID);

ALTER TABLE Lamp
ADD CONSTRAINT Lamp_Sensor
FOREIGN KEY (SensorID) REFERENCES Sensor(SensorID);
